[package]
name = "lalir"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "svd_benchmark"
harness = false  # Disable the default test harness so Criterion can take over
